### PR TITLE
Cant open Google Play Store

### PR DESCRIPTION
**Pull request by MidnightTempest**
Title says it, just installed your ROM  on SM-J510FN

### CODE REVIEW

**Comment by GentritU** [comment]
You're totally wrong, first of all Vince's rom doesn't support your model, second you don't have to report bugs in github, you can do it on the rom thread(the correct one for your phone).
And no, a play store error is most likely gapps issue.

**Comment by gerrit-galaxy-msm8916** [comment]
@GentritU Oh, i thought we closed this already. But yeah, I was wondering if he got the device model wrong or something.

**Comment by vlw** [comment]
@GentritU Google Play issue not kernel-related

**Comment by bartcubbins** [comment]
@MidnightTempest just a couple of commits from this pr can be merged another one are not safe and I think this will never be merged, sorry

**Pull request closed without merging**
